[project]
name = "djavite"
version = "0.1.0"
description = "A library for seamless integration of Vite with Django, enabling modern frontend tooling in Django projects."
readme = "README.md"
authors = [
    { name = "Muhammad Iqbal", email = "iqbal.adudu@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.7",
    "honcho>=2.0.0",
]

license = "MIT"

[tool.hatch.build.targets.wheel]
packages = ["vite"]

[project.scripts]
djavite = "djavite:main"

[tool.hatch.build.targets.sdist]
include = ["README.md", "LICENSE", "Procfile", "src/vite/**"]
exclude = ["uv.lock"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
